### ISSUE TITLE
关于训练精度不太理想

### ISSUE THREAD

**Issue by lovingpolar** [DingJianhao/OptSNNConvertion-RNL-RIL#1]
您好！我训练了vgg16_cifar10的部分，但是精度不理想只有0.1，请问我有什么地方需要特别注意的吗？

**Comment by DingJianhao** [comment]
训练的时候可以一边训练 一边存模型 随着训练进行准确率会下降

**Comment by JominWink** [comment]
在训练阶段精确度一直在0.1，没有提升过，请问下是什么问题？

**Comment by DingJianhao** [comment]
我猜可能load错模型了？或者load模型后scale设置错了。 @JominWink

**Comment by DingJianhao** [comment]
可以试试[tutorial.py](https://github.com/DingJianhao/OptSNNConvertion-RNL-RIL/blob/main/tutorial.py)

**Comment by JominWink** [comment]
> 

用tutorial.py替换掉para_train.py吗？我是运行你给的初始的参数，没有修改任何值。

**Comment by DingJianhao** [comment]
tutorial.py 相当于就是模型para_train+fast_train的一个整合版本。运行完tutorial.py了解了大概后，你就可以自己设置喜欢的超参数了

**Comment by JominWink** [comment]
对于文章中的两个阶段训练模式，在代码中是整合到一次了吗

**Comment by DingJianhao** [comment]
对

**Comment by JominWink** [comment]
所以在第一次训练ANN的时候也可以把阈值训练好吗？那这样的话怎么确保ANN训练出的发放率是最优的？

**Comment by DingJianhao** [comment]
论文里写了啊 第二阶段训练目标是保持激活cos同时调优发放率啊 发放率最优因为第二阶段加了对应的RIL 想同时训练精度和高发放率也可以试试

**Comment by JominWink** [comment]
好的，我再细读一下文章，辛苦了

**Comment by DingJianhao** [comment]
要养成先仔细看论文后求助的好习惯呢

**Comment by JominWink** [comment]
好的！多谢指点
